### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by urosgruber** [bsdci/ioc#28] opened 2019-04-04 18:08 UTC
I just pulled latest master and yesterday I spend half a day debugging what is going on. So the thing is that after `make install` I have `ioc` that is missing couple of commands

```
Usage: ioc [OPTIONS] COMMAND [ARGS]...

  A jail manager.

Options:
  --version             Show the version and exit.
  --source TEXT         Globally override the activated iocage dataset(s)
  -d, --log-level TEXT  Set the CLI log level ('critical', 'error', 'warn',
                        'info', 'notice', 'verbose', 'debug', 'spam',
                        'screen')
  --help                Show this message and exit.

Commands:
  activate    Set a zpool active for iocage usage.
  deactivate  Disable a ZFS pool for libioc.
  fstab       View and manipulate a jails fstab file.
  get         Gets the specified property.
  import      Import a jail from a backup archive
  migrate     Migrate jails to the latest format.
  pkg         Manage packages in a jail.
  promote     Clone and promote jails.
  provision   Trigger provisioning of jails.
  rename      Rename a stopped jail.
  restart     Restarts the specified jails.
  set         Sets the specified property.
  snapshot    Take and manage resource snapshots.
  start       Starts the specified jails or ALL.
  stop        Stops the specified jails or ALL.
  update      Update a jail to a new release or patchlevel.
```  

I then checked out older versions and all of a sudden I got back all the commands, and even if I try to fetch latest master. Today I did pull latest master on new server and *bam* Again missing commands. Can you please help me understand what is going on here and what am I doing wrong.

**Comment by urosgruber** [comment] 2019-04-04 18:13
🤦🏻‍♂️ I guess I needed to write it here to find a real cause. I think this is a bug. So reason for this is missing *py-ucl* So after installing this everything started to work right away. So something must be wrong in Makefile or even missing a requirement because I need to install this manually. Would be nice if this works without this if using latest config where I believe this is not needed at all. Am I right?

**Comment by gronke** [comment] 2019-04-04 20:57
@urosgruber you stubled into a bug that also hit @foo2342. I'm currently investigating the cause and was not able so far to reproduce this on one of my machines.

**Comment by foo2342** [comment] 2019-04-04 21:15
That's a fun one. I had to downgrade libucl to 0.8.0, then everything worked fine. I think we should get rid of this dependency.

**Comment by gronke** [comment] 2019-04-04 21:21
@urosgruber can you please run this command and check the output?

```console
$ python3.6 -c "import ucl; print(ucl.load('foo: bar'))"
{'foo': 'bar'}
```

I have just upgraded `libucl: 0.8.0 -> 0.8.1 [FreeBSD]` from latest and it still works.

**Comment by gronke** [comment] 2019-04-05 02:44
Finally I was able to reproduce this on a FreeBSD 12 build from stable/12.

```console
# python3.6 -c "import ucl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Shared object "libucl.so.6" not found, required by "ucl.so"
```

The upstream bug was filed as https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237029

**Comment by urosgruber** [comment] 2019-04-05 04:37
As I said, as soon as I install `py-ucl` from ports all is good. The command you ask give me 

`{'foo': 'bar'}`

And this is what I have installed
```
libucl-0.8.1                       =   up-to-date with remote
py36-ucl-0.8.1_1                   =   up-to-date with remote
```

**Comment by gronke** [comment] 2019-04-05 14:16
fixed in https://github.com/bsdci/libioc/pull/701

**Closed by gronke** 2019-04-05 14:16 UTC
